# development:
#   google_client_id: 620608337996-ao0ggq82kcqgbt76j5kinkv2s79ijrja.apps.googleusercontent.com
#   google_client_secret: S-2SniiK6EyMvV4h_xDAP_O9

#   facebook_client_id: 338246616822614
#   facebook_client_secret: ce7a325198e0cb9ea07c112ef909ed66
